MYSQL:
  HOST: 159.89.134.14
  PORT: 3306
  USER: python
  PASSWD: prensa2018
  DB: press

TABLES:
  QUEUE: queue
  PROCESSED: processed
  RESULT: press
  ERROR: error
  BACKUP: all_links

SOURCES:
- Emol
- Biobiochile
- Df
- Cooperativa
- Latercera
- Elmostrador

CONFIG:
  DEBUG: false
