MYSQL:
    HOST: null
    PORT: 3306
    USER: null
    PASSWD: null
    DB: null
    
TABLES:
    QUEUE: queue
    PROCESSED: processed
    RESULT: press
    ERROR: error
    BACKUP: all_links

SOURCES:
    - Emol
    - Biobiochile
    - Df
    - Cooperativa
    - Latercera
    - Elmostrador

CONFIG:
    DEBUG: False